version: "3.9"

services:
  news_server_database:
    image: postgres:15
    container_name: news_server_database
    volumes:
      - ~/python/.pg/server_database:/var/lib/postgresql/data

    env_file:
    - .env
    ports:
    -  5433:5432

  news_server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: news_server
    depends_on:
      - news_server_database
    env_file:
      - .env
    command: >
      bash -c "python3 manage.py migrate && python3 manage.py loaddata ./fixtures/admin.json && python3 manage.py runserver 0.0.0.0:8000"
    ports:
    - 8000:8000
