# Generated by Django 4.2.3 on 2023-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_catrgory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['id', 'tag_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'category_name']},
        ),
    ]
