# Generated by Django 4.2.3 on 2023-09-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
    ]
