#  make author

POST  http://127.0.0.1:8000/api/authors/  HTTP/1.1
content-type: application/json
token: ee497287-a496-4a2b-8425-b40cd865ee10

{
    "id": 2,
    "bio": "hello world1"
}

###

#  get authors

GET  http://127.0.0.1:8000/api/authors/  HTTP/1.1

###

#  delete author

DELETE  http://127.0.0.1:8000/api/authors/2/  HTTP/1.1
content-type: application/json
token: ee497287-a496-4a2b-8425-b40cd865ee10

###

#  update author

PUT  http://127.0.0.1:8000/api/authors/2/  HTTP/1.1
content-type: application/json
token: ee497287-a496-4a2b-8425-b40cd865ee10

{
    "bio": "cringe"
}

###