#  make author

POST  http://127.0.0.1:8000/api/authors/  HTTP/1.1
content-type: application/json
token: 9772a0c6-29d6-4903-a392-82a50074df7f

{
    "id": 1,
    "bio": "hello world1"
}

###

#  get authors

GET  http://127.0.0.1:8000/api/authors/  HTTP/1.1

###

#  delete author

DELETE  http://127.0.0.1:8000/api/authors/?id=2  HTTP/1.1
content-type: application/json
token: 0db5a3ab-2a90-4cab-8cab-f388b1ac0d70

###

#  update author

PUT  http://127.0.0.1:8000/api/authors/  HTTP/1.1
content-type: application/json

{
    "bio": "cringe",
    "id": 1
}

###