# @name make author

POST  http://127.0.0.1:8000/api/authors/  HTTP/1.1
content-type: application/json
token: 2c8cb969-3994-426f-8271-3cc73950b713

{
    "id": 1,
    "bio": "hello world"
}

###

# @name get authors

GET  http://127.0.0.1:8000/api/authors/  HTTP/1.1

###

# @name delete author

DELETE  http://127.0.0.1:8000/api/authors/?id=2  HTTP/1.1
content-type: application/json
token: 0db5a3ab-2a90-4cab-8cab-f388b1ac0d70

###

# @name update author

PUT  http://127.0.0.1:8000/api/authors/  HTTP/1.1
content-type: application/json

{
    "bio": "cringe",
    "id": 1
}

###