#  add category
POST  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json
token: 881e6787-506a-4957-a674-47e31b2b481e

{
    "category_name": "Sport"
}

###

#  get categories

GET  http://127.0.0.1:8000/api/categories/  HTTP/1.1

###

#  update categories

PUT  http://127.0.0.1:8000/api/categories/1/  HTTP/1.1
content-type: application/json
token: 881e6787-506a-4957-a674-47e31b2b481e

{
    "category_name": "Sport"
}

###

#  delete categories

DELETE  http://127.0.0.1:8000/api/categories/1/  HTTP/1.1
content-type: application/json
token: 881e6787-506a-4957-a674-47e31b2b481e
###