# @name add category
POST  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json

{
    "category_name": "Football1",
    "token": "cd61d773-abfe-44e3-ae30-84ec225c9bcf"
}

###

# @name get categories

GET  http://127.0.0.1:8000/api/categories/  HTTP/1.1

###

# @name update categories

PUT  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json

{
    "category_name": "Baseball",
    "id": 1
}

###

# @name delete categories

DELETE  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json

{
    "id": 1
}

###