#  add category
POST  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json
token: 9772a0c6-29d6-4903-a392-82a50074df7f

{
    "category_name": "Football",
    "parent_category": 1
}

###

#  get categories

GET  http://127.0.0.1:8000/api/categories/?page=9  HTTP/1.1

###

#  update categories

PUT  http://127.0.0.1:8000/api/categories/  HTTP/1.1
content-type: application/json
token: 2d13ee53-d1a1-40fe-b1a3-5e2f36cad9e7

{
    "category_name": "Baseball",
    "id": 3
}

###

#  delete categories

DELETE  http://127.0.0.1:8000/api/categories/?id=4  HTTP/1.1
content-type: application/json
token: 2d13ee53-d1a1-40fe-b1a3-5e2f36cad9e7
###