###

# add draft

POST /api/drafts/ HTTP/1.1
Host: localhost:8000
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
token: e38cdfbc-0686-4604-afa6-000f19aa8e99

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

news_title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

something
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="new.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="another.png"
Content-Type: image/png

< ./2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# delete draft

DELETE  http://127.0.0.1:8000/api/drafts/?id=3  HTTP/1.1
content-type: application/json
token: e38cdfbc-0686-4604-afa6-000f19aa8e99

###

# get list of drafts

GET  http://127.0.0.1:8000/api/drafts/  HTTP/1.1
token: e38cdfbc-0686-4604-afa6-000f19aa8e90

###