

# get news list

GET  http://127.0.0.1:8000/api/news/  HTTP/1.1

###

# delete news

DELETE  http://127.0.0.1:8000/api/news/?id=4  HTTP/1.1
content-type: application/json
token: e38cdfbc-0686-4604-afa6-000f19aa8e99

###

# publish news

POST  http://127.0.0.1:8000/api/news/?id=1  HTTP/1.1
content-type: application/json
token: b44db732-08a1-44ae-9895-d6355fbbdb77

###


# get news 

GET  http://127.0.0.1:8000/api/news/1  HTTP/1.1

###

# get news 

GET  http://127.0.0.1:8000/api/list_of_news/?page=2  HTTP/1.1

###