# @name add tags
POST  http://127.0.0.1:8000/api/tags/  HTTP/1.1
content-type: application/json
token: c63c58f6-074d-46c4-ae8f-53dbcbe392a0

{
    "tag_name": "base"
}

###

# @name get tags

GET  http://127.0.0.1:8000/api/tags/  HTTP/1.1

###

# @name update tag

PUT  http://127.0.0.1:8000/api/tags/  HTTP/1.1
content-type: application/json

{
    "tag_name": "hahah",
    "id": 1
}

###

# @name delete tag

DELETE  http://127.0.0.1:8000/api/tags/?id=2  HTTP/1.1
content-type: application/json


###