# @name add category
POST  http://127.0.0.1:8000/category/  HTTP/1.1
content-type: application/json

{
    "category_name": "Football",
    "parent_category": 1
}

###

# @name get categories

GET  http://127.0.0.1:8000/category/  HTTP/1.1