# @name add category
POST  http://127.0.0.1:8000/category/  HTTP/1.1
content-type: application/json

{
    "category_name": "Football",
    "parent_category": 1
}

###

# @name get categories

GET  http://127.0.0.1:8000/category/  HTTP/1.1

###

# @name update categories

PUT  http://127.0.0.1:8000/category/  HTTP/1.1
content-type: application/json

{
    "category_name": "Football",
    "id": 2
}

###


# @name add tags
POST  http://127.0.0.1:8000/tags/  HTTP/1.1
content-type: application/json

{
    "tag_name": "cringe"
}

###

# @name get tags

GET  http://127.0.0.1:8000/tags/  HTTP/1.1

###

# @name update tag

PUT  http://127.0.0.1:8000/tags/  HTTP/1.1
content-type: application/json

{
    "tag_name": "base",
    "id": 1
}

###

# @name registration

POST  http://127.0.0.1:8000/user/  HTTP/1.1
content-type: application/json

{
    "first_name": "first_name",
    "last_name": "last_name",
    "username": "username",
    "password": "password",
    "email": "email"
}

###

# @name users list

GET  http://127.0.0.1:8000/user/  HTTP/1.1

###