###

# @name registration

POST  http://127.0.0.1:8000/user/  HTTP/1.1
content-type: application/json

{
    "first_name": "first_name",
    "last_name": "last_name",
    "username": "username",
    "password": "password",
    "email": "email@email.com"
}

###

# @name users list

GET  http://127.0.0.1:8000/user/list/  HTTP/1.1

###

# @name delete user

DELETE  http://127.0.0.1:8000/user/  HTTP/1.1
content-type: application/json
token: 8d913a49-3ba3-4c8a-acbe-154fe54ff28a

{
    "id": 3
}

###

# @name login

GET  http://127.0.0.1:8000/login/  HTTP/1.1
content-type: application/json

{
    "username": "username",
    "password": "password"
}

###

# @name user info

GET  http://127.0.0.1:8000/user/  HTTP/1.1
content-type: application/json
token: 8d913a49-3ba3-4c8a-acbe-154fe54ff28a

###

# @name check token

GET  http://127.0.0.1:8000/user/check_token  HTTP/1.1
token: a51cecd6-710a-4a05-be6f-c42841b4a279

###