###

# registration

POST  http://127.0.0.1:8000/api/users/  HTTP/1.1
content-type: application/json

{
    "first_name": "first_name1",
    "last_name": "last_name1",
    "username": "username1",
    "password": "password",
    "email": "email@email.com"
}

###

#  users list

GET  http://127.0.0.1:8000/api/users/  HTTP/1.1

###

#  delete user

DELETE  http://127.0.0.1:8000/api/users/?id=1  HTTP/1.1
content-type: application/json
token: a3341de7-b3bf-4b18-9dce-ab1c922389e0

###

#  login

POST  http://127.0.0.1:8000/api/login/  HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

#  profile info

GET  http://127.0.0.1:8000/api/profile/  HTTP/1.1
content-type: application/json
token: 45922674-a269-43c6-bcbe-362fec3cce3c

###