###

# registration

POST  http://127.0.0.1:8000/api/users/  HTTP/1.1
content-type: application/json

{
    "first_name": "first_name",
    "last_name": "last_name",
    "username": "username",
    "password": "password",
    "email": "email@email.com"
}

###

#  users list

GET  http://127.0.0.1:8000/api/users/  HTTP/1.1

###

#  user info

GET  http://127.0.0.1:8000/api/users/1/  HTTP/1.1

###

#  delete user

DELETE  http://127.0.0.1:8000/api/users/2/  HTTP/1.1
content-type: application/json
token: e8550739-8c12-4c95-8e8c-6c2c9564ac57

###

#  login

POST  http://127.0.0.1:8000/api/login/  HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###